//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaVeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaVeGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AD转化 {
            get {
                object obj = ResourceManager.GetObject("AD转化", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Code {
            get {
                object obj = ResourceManager.GetObject("Code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comply {
            get {
                object obj = ResourceManager.GetObject("comply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controls {
            get {
                object obj = ResourceManager.GetObject("controls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DA转化 {
            get {
                object obj = ResourceManager.GetObject("DA转化", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OFF延时 {
            get {
                object obj = ResourceManager.GetObject("OFF延时", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ON延时 {
            get {
                object obj = ResourceManager.GetObject("ON延时", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PID控制器 {
            get {
                object obj = ResourceManager.GetObject("PID控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RS触发器 {
            get {
                object obj = ResourceManager.GetObject("RS触发器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 一阶传递函数 {
            get {
                object obj = ResourceManager.GetObject("一阶传递函数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 三者取中器 {
            get {
                object obj = ResourceManager.GetObject("三者取中器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 三输入ON有效或门 {
            get {
                object obj = ResourceManager.GetObject("三输入ON有效或门", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 三输入不一致 {
            get {
                object obj = ResourceManager.GetObject("三输入不一致", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 不等于比较 {
            get {
                object obj = ResourceManager.GetObject("不等于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 两输入ON有效或门 {
            get {
                object obj = ResourceManager.GetObject("两输入ON有效或门", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 乘幂 {
            get {
                object obj = ResourceManager.GetObject("乘幂", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 乘法 {
            get {
                object obj = ResourceManager.GetObject("乘法", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 余切 {
            get {
                object obj = ResourceManager.GetObject("余切", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 余弦 {
            get {
                object obj = ResourceManager.GetObject("余弦", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 偏差限值器 {
            get {
                object obj = ResourceManager.GetObject("偏差限值器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 减法 {
            get {
                object obj = ResourceManager.GetObject("减法", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 前馈器 {
            get {
                object obj = ResourceManager.GetObject("前馈器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 加权平均滤波器 {
            get {
                object obj = ResourceManager.GetObject("加权平均滤波器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 加法 {
            get {
                object obj = ResourceManager.GetObject("加法", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 反余弦 {
            get {
                object obj = ResourceManager.GetObject("反余弦", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 反正切 {
            get {
                object obj = ResourceManager.GetObject("反正切", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 反正弦 {
            get {
                object obj = ResourceManager.GetObject("反正弦", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 取整 {
            get {
                object obj = ResourceManager.GetObject("取整", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 变化检测 {
            get {
                object obj = ResourceManager.GetObject("变化检测", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 变化率器 {
            get {
                object obj = ResourceManager.GetObject("变化率器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大于比较 {
            get {
                object obj = ResourceManager.GetObject("大于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大于等于比较 {
            get {
                object obj = ResourceManager.GetObject("大于等于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大林控制器 {
            get {
                object obj = ResourceManager.GetObject("大林控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 定长度脉冲 {
            get {
                object obj = ResourceManager.GetObject("定长度脉冲", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小于比较 {
            get {
                object obj = ResourceManager.GetObject("小于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小于等于比较 {
            get {
                object obj = ResourceManager.GetObject("小于等于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 常数 {
            get {
                object obj = ResourceManager.GetObject("常数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 常用对数 {
            get {
                object obj = ResourceManager.GetObject("常用对数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 平方根 {
            get {
                object obj = ResourceManager.GetObject("平方根", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 延时 {
            get {
                object obj = ResourceManager.GetObject("延时", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 开关 {
            get {
                object obj = ResourceManager.GetObject("开关", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 开关控制器13 {
            get {
                object obj = ResourceManager.GetObject("开关控制器13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 开关控制器51 {
            get {
                object obj = ResourceManager.GetObject("开关控制器51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 指数 {
            get {
                object obj = ResourceManager.GetObject("指数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字组合器 {
            get {
                object obj = ResourceManager.GetObject("数字组合器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字输入 {
            get {
                object obj = ResourceManager.GetObject("数字输入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 数字输出 {
            get {
                object obj = ResourceManager.GetObject("数字输出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 斜坡控制器 {
            get {
                object obj = ResourceManager.GetObject("斜坡控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最大时限脉冲 {
            get {
                object obj = ResourceManager.GetObject("最大时限脉冲", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最小时限脉冲 {
            get {
                object obj = ResourceManager.GetObject("最小时限脉冲", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最少拍控制器 {
            get {
                object obj = ResourceManager.GetObject("最少拍控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 条件动作表 {
            get {
                object obj = ResourceManager.GetObject("条件动作表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 模拟输入 {
            get {
                object obj = ResourceManager.GetObject("模拟输入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 模拟输出 {
            get {
                object obj = ResourceManager.GetObject("模拟输出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 模糊控制器 {
            get {
                object obj = ResourceManager.GetObject("模糊控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 正切 {
            get {
                object obj = ResourceManager.GetObject("正切", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 正弦 {
            get {
                object obj = ResourceManager.GetObject("正弦", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 比例器 {
            get {
                object obj = ResourceManager.GetObject("比例器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 比值控制器 {
            get {
                object obj = ResourceManager.GetObject("比值控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 比较器 {
            get {
                object obj = ResourceManager.GetObject("比较器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 求余 {
            get {
                object obj = ResourceManager.GetObject("求余", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 注释 {
            get {
                object obj = ResourceManager.GetObject("注释", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 温压补偿器 {
            get {
                object obj = ResourceManager.GetObject("温压补偿器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 滤波 {
            get {
                object obj = ResourceManager.GetObject("滤波", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 看门狗 {
            get {
                object obj = ResourceManager.GetObject("看门狗", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 等于比较 {
            get {
                object obj = ResourceManager.GetObject("等于比较", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 系统变量 {
            get {
                object obj = ResourceManager.GetObject("系统变量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 累计器 {
            get {
                object obj = ResourceManager.GetObject("累计器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 纯滞后补偿器 {
            get {
                object obj = ResourceManager.GetObject("纯滞后补偿器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 线性变换器 {
            get {
                object obj = ResourceManager.GetObject("线性变换器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绝对值 {
            get {
                object obj = ResourceManager.GetObject("绝对值", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 脉冲输入 {
            get {
                object obj = ResourceManager.GetObject("脉冲输入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 脉宽调制输出 {
            get {
                object obj = ResourceManager.GetObject("脉宽调制输出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自然对数 {
            get {
                object obj = ResourceManager.GetObject("自然对数", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 解耦补偿控制器 {
            get {
                object obj = ResourceManager.GetObject("解耦补偿控制器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 计数器 {
            get {
                object obj = ResourceManager.GetObject("计数器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 计时器 {
            get {
                object obj = ResourceManager.GetObject("计时器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 计算器组态 {
            get {
                object obj = ResourceManager.GetObject("计算器组态", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 调用 {
            get {
                object obj = ResourceManager.GetObject("调用", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 跳转 {
            get {
                object obj = ResourceManager.GetObject("跳转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输入变量 {
            get {
                object obj = ResourceManager.GetObject("输入变量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输出变量 {
            get {
                object obj = ResourceManager.GetObject("输出变量", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 返回 {
            get {
                object obj = ResourceManager.GetObject("返回", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 选通器 {
            get {
                object obj = ResourceManager.GetObject("选通器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 通用线性化器 {
            get {
                object obj = ResourceManager.GetObject("通用线性化器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑与 {
            get {
                object obj = ResourceManager.GetObject("逻辑与", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑与非 {
            get {
                object obj = ResourceManager.GetObject("逻辑与非", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑异或 {
            get {
                object obj = ResourceManager.GetObject("逻辑异或", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑或 {
            get {
                object obj = ResourceManager.GetObject("逻辑或", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑或非 {
            get {
                object obj = ResourceManager.GetObject("逻辑或非", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 逻辑非 {
            get {
                object obj = ResourceManager.GetObject("逻辑非", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 限值器 {
            get {
                object obj = ResourceManager.GetObject("限值器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 除法 {
            get {
                object obj = ResourceManager.GetObject("除法", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 高低选择器 {
            get {
                object obj = ResourceManager.GetObject("高低选择器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
